apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  type: NodePort
  selector:
    app: tenant-app
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30003